name: 'Lint'
description: An opinionated GitHub Action starter template
inputs:
  repo-token:
    description: 'github security token'
    required: true
  custom-directory:
    description: 'relative directory to node_modules'
    required: true
  eslint-config-path:
    description: 'relative path to eslint config file eg. .eslintrc'
    required: true
  eslintignore-path:
    description: 'relative path to .eslintignore'
    required: true

runs:
  using: 'node16'
  main: 'index.mjs'

branding:
  icon: 'check-circle'
  color: 'blue'