name: On code change

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  run-unit-tests:
    uses: tinovyatkin/action-eslint@v1
    with:
      repo-token: ${{secrets.GITHUB_TOKEN}}
      check-name: eslint # this is the check name from above 👆 where to post annotations